# Setup
Install basic dependenciesx

In [34]:
import pandas as pd
import numpy as np
from IPython.display import Markdown, display


# Display settings for pandas
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.4f}'.format)

## Settings

How many students per team?

In [35]:
STUDENTS_PER_TEAM = 5

Input and output data filenames

In [36]:
INPUT_FILE = 'data/student-preferences-spring2026.csv'
OUTPUT_FILE = 'data/project_assignments_spring2026.csv'

## Load input data

A blank dataframe that will hold each student's assigned project once done

In [37]:
df_assignments = pd.DataFrame(columns=['email', 'project', 'own'])

Load the input data file into a dataframe

In [38]:
df_votes = pd.read_csv(INPUT_FILE)

Simplify column names and remove unnecessary columns.

In [39]:
df_votes = df_votes.rename(columns={
    'Email Address': 'email',
    'First choice': 'first',
    'Second choice': 'second',
    'Third choice': 'third',
    'Are any of these choices your own project proposal?': 'voted_for_self'
})[['email', 'first', 'second', 'third', 'voted_for_self']]

Remove all before a dash and trim whitespace... this is specific to how the project names are followed by their descriptions... remove or update as needed.

In [40]:
for col in ['first', 'second', 'third']:
    df_votes[col] = df_votes[col].str.split('-').str[0].str.strip()

Convert all project names to lowercase.

In [41]:
for col in ['first', 'second', 'third']:
    df_votes[col] = df_votes[col].str.lower()

Take a gander.

In [42]:
df_votes.sample(5)

,email,first,second,third,voted_for_self
0,am12611@nyu.edu,planit,studyspot,budgetlife,Yes - Second choice
66,ymm9035@nyu.edu,syllabus+,skill swipe,student expense tracker,No - I did not select my own project proposal ...
18,cl6577@nyu.edu,milely,oh queue,subvet,Yes - First choice
28,aa10027@nyu.edu,budgetlife,jamsesh,vixu,Yes - First choice
12,jaj9365@nyu.edu,feedbackloop,vixu,planit,Yes - Third choice

## Determine project names

In [43]:
project_names = pd.Series(pd.unique(df_votes[['first', 'second', 'third']].values.ravel()))

In [44]:
project_names = project_names.str.lower()

In [45]:
project_names.describe()

count         28
unique        28
top       planit
freq           1
dtype: object

In [46]:
project_names.sample(3)

2     budgetlife
11       jamsesh
17        subvet
dtype: object

## Count votes

Total number of first, second, and third choice votes for each project.

In [47]:
def get_remaining_vote_counts(df_votes):
    vote_counts = pd.DataFrame({
        'project': project_names,
        'first_count': [df_votes['first'].str.lower().eq(name).sum() for name in project_names],
        'second_count': [df_votes['second'].str.lower().eq(name).sum() for name in project_names],
        'third_count': [df_votes['third'].str.lower().eq(name).sum() for name in project_names]
    })
    vote_counts['total'] = vote_counts['first_count'] + vote_counts['second_count'] + vote_counts['third_count']

    vote_counts.sort_values(
        by=['first_count', 'second_count', 'third_count'],
        ascending=[False, False, False]
    )
    return vote_counts

In [48]:
vote_counts = get_remaining_vote_counts(df_votes)
vote_counts

,project,first_count,second_count,third_count,total
0,planit,3,4,7,14
1,studyspot,2,3,2,7
2,budgetlife,6,3,2,11
3,pairup/matchforge,5,3,7,15
4,paddock,1,3,2,6
5,healthmate – practical health and fitness mana...,0,3,2,5
6,stop booking start cooking,4,1,3,8
7,feedbackloop,7,4,2,13
8,internbuddy,9,4,5,18
9,milely,1,1,1,3
10,newstoaction,1,3,2,6
11,jamsesh,1,6,1,8
12,student expense tracker,4,4,4,12
13,skill swipe,1,2,2,5
14,studysync,4,1,2,7
15,peerly,3,0,1,4
16,vixu,0,8,4,12
17,subvet,0,1,4,5
18,capturing,4,1,2,7
19,swap,1,2,2,5
20,syllabus+,4,0,4,8
21,meetpoint,3,3,1,7
22,runwise – adaptive marathon training + injury,2,0,2,4
23,oh queue,1,2,1,4
24,studygroups,0,2,0,2
25,soft launch,1,1,0,2
26,pocketplan,0,4,3,7
27,studysprint,1,0,1,2

Identify projects with insufficient votes

In [49]:
# Identify projects with insufficient total votes
vote_counts = get_remaining_vote_counts(df_votes)
insufficient_projects = vote_counts[vote_counts['total'] < STUDENTS_PER_TEAM][['project', 'total']]
insufficient_projects

                                          project  total
9                                          milely      3
15                                         peerly      4
22  runwise – adaptive marathon training + injury      4
23                                       oh queue      4
24                                    studygroups      2
25                                    soft launch      2
27                                    studysprint      2

Remove those projects with insufficient votes from the vote counts.

In [50]:

# Remove these projects from vote_counts
vote_counts = vote_counts[~vote_counts['project'].isin(insufficient_projects['project'])].reset_index(drop=True)
vote_counts

,project,first_count,second_count,third_count,total
0,planit,3,4,7,14
1,studyspot,2,3,2,7
2,budgetlife,6,3,2,11
3,pairup/matchforge,5,3,7,15
4,paddock,1,3,2,6
5,healthmate – practical health and fitness mana...,0,3,2,5
6,stop booking start cooking,4,1,3,8
7,feedbackloop,7,4,2,13
8,internbuddy,9,4,5,18
9,newstoaction,1,3,2,6
10,jamsesh,1,6,1,8
11,student expense tracker,4,4,4,12
12,skill swipe,1,2,2,5
13,studysync,4,1,2,7
14,vixu,0,8,4,12
15,subvet,0,1,4,5
16,capturing,4,1,2,7
17,swap,1,2,2,5
18,syllabus+,4,0,4,8
19,meetpoint,3,3,1,7
20,pocketplan,0,4,3,7

Remove mention of those projects from df_votes.

In [51]:
for project in insufficient_projects:
    for col in ['first', 'second', 'third']:
        df_votes.loc[df_votes[col] == project, col] = np.nan

df_votes.sample(10)

,email,first,second,third,voted_for_self
67,wg823@nyu.edu,capturing,newstoaction,pairup/matchforge,No - I did not select my own project proposal ...
45,fcw2020@nyu.edu,skill swipe,swap,pocketplan,No - I did not select my own project proposal ...
48,ml9389@nyu.edu,oh queue,vixu,feedbackloop,No - I did not select my own project proposal ...
38,ae2506@nyu.edu,soft launch,pocketplan,internbuddy,Yes - First choice
29,zyc2270@nyu.edu,budgetlife,jamsesh,vixu,Yes - First choice
60,jp6393@nyu.edu,studyspot,planit,internbuddy,No - I did not select my own project proposal ...
42,sd4994@nyu.edu,runwise – adaptive marathon training + injury,student expense tracker,pairup/matchforge,No - I did not select my own project proposal ...
32,cac10199@nyu.edu,internbuddy,soft launch,pocketplan,No - I did not select my own project proposal ...
65,ma7759@nyu.edu,budgetlife,pocketplan,jamsesh,No - I did not select my own project proposal ...
30,yw6861@nyu.edu,budgetlife,paddock,feedbackloop,Yes - First choice

## New method

In [52]:
def get_project_votes(df_votes, project):
    """
    Returns a dataframe of all rows where the first, second, or third choices were the given project.
    Orders results according to vote priority.    

    """
    df = df_votes.copy()
    df['sort_priority'] = np.select(
        [
            # first choice and wrote it themselves
            (df['first'] == project) & (df['voted_for_self'] == 'Yes - First choice'),
            # first choice but didn't write it
            (df['first'] == project) & (df['voted_for_self'] != 'Yes - First choice'),
            # second choice and wrote it themselves
            (df['second'] == project) & (df['voted_for_self'] == 'Yes - Second choice'),
            # second choice but didn't write it
            (df['second'] == project) & (df['voted_for_self'] != 'Yes - Second choice'),
            # third choice and wrote it themselves
            (df['third'] == project) & (df['voted_for_self'] == 'Yes - Third choice'),
            # third choice but didn't write it
            (df['third'] == project) & (df['voted_for_self'] != 'Yes - Third choice')
        ],
        [6, 5, 4, 3, 2, 1],
        default=0
    )
    mask = (
        (df['first'] == project) |
        (df['second'] == project) |
        (df['third'] == project)
    )
    return df[mask].sort_values(by='sort_priority', ascending=False).reset_index(drop=True)

In [53]:
# a function to check whether a team is full
def is_team_full(df_assignments, project):
    """
    Check if the given project team in df_assignments has reached the maximum number of students.
    Returns True if the team is full, otherwise False.
    """
    return df_assignments[df_assignments['project'] == project].shape[0] >= STUDENTS_PER_TEAM

In [54]:
# Assign students to projects based on their votes and self-proposal status

assigned_emails = set(df_assignments['email'])
projects = vote_counts['project'].tolist()

for priority in range(6):
    for project in projects:
        if is_team_full(df_assignments, project):
            continue
        # Select students based on priority
        if priority == 0:
            mask = (
                (df_votes['first'] == project) &
                (df_votes['voted_for_self'] == 'Yes - First choice')
            )
        elif priority == 1:
            mask = (
                (df_votes['first'] == project) &
                (df_votes['voted_for_self'] != 'Yes - First choice')
            )
        elif priority == 2:
            mask = (
                (df_votes['second'] == project) &
                (df_votes['voted_for_self'] == 'Yes - Second choice')
            )
        elif priority == 3:
            mask = (
                (df_votes['second'] == project) &
                (df_votes['voted_for_self'] != 'Yes - Second choice')
            )
        elif priority == 4:
            mask = (
                (df_votes['third'] == project) &
                (df_votes['voted_for_self'] == 'Yes - Third choice')
            )
        elif priority == 5:
            mask = (
                (df_votes['third'] == project) &
                (df_votes['voted_for_self'] != 'Yes - Third choice')
            )
        candidates = df_votes[mask & (~df_votes['email'].isin(assigned_emails))]
        for _, row in candidates.iterrows():
            if is_team_full(df_assignments, project):
                break
            df_assignments.loc[len(df_assignments)] = {
                'email': row['email'],
                'project': project,
                'own': (
                    (priority == 0) or
                    (priority == 2) or
                    (priority == 4)
                )
            }
            assigned_emails.add(row['email'])

In [55]:

# Function to redistribute remaining votes
df_assignments.sort_values(by=['project', 'own', 'email'])

               email                                            project    own
29    ml8397@nyu.edu                                         budgetlife  False
30    st4816@nyu.edu                                         budgetlife  False
0    aa10027@nyu.edu                                         budgetlife   True
2     yw6861@nyu.edu                                         budgetlife   True
1    zyc2270@nyu.edu                                         budgetlife   True
47    at6055@nyu.edu                                          capturing  False
46    hj2743@nyu.edu                                          capturing  False
48     wg823@nyu.edu                                          capturing  False
19    sy3544@nyu.edu                                          capturing   True
35    ag8969@nyu.edu                                       feedbackloop  False
37    fh2303@nyu.edu                                       feedbackloop  False
34   jaj9365@nyu.edu                                       feedbackloop  False
36   ngm9720@nyu.edu                                       feedbackloop  False
10    sz3832@nyu.edu                                       feedbackloop   True
63    lcs493@nyu.edu  healthmate – practical health and fitness mana...  False
38    aw5571@nyu.edu                                        internbuddy  False
11    aw5287@nyu.edu                                        internbuddy   True
12    fl2367@nyu.edu                                        internbuddy   True
13    gh2313@nyu.edu                                        internbuddy   True
14    st4966@nyu.edu                                        internbuddy   True
56   knp4830@nyu.edu                                            jamsesh  False
40    lj1353@nyu.edu                                            jamsesh  False
52   smh9864@nyu.edu                                          meetpoint  False
22    mw5608@nyu.edu                                          meetpoint   True
23    tq2098@nyu.edu                                          meetpoint   True
55   dpp9951@nyu.edu                                       newstoaction  False
39   itd2007@nyu.edu                                       newstoaction  False
54    up2040@nyu.edu                                            paddock  False
8    san7576@nyu.edu                                            paddock   True
5     el3798@nyu.edu                                  pairup/matchforge   True
3     jk8308@nyu.edu                                  pairup/matchforge   True
4     rm6283@nyu.edu                                  pairup/matchforge   True
7    sl10716@nyu.edu                                  pairup/matchforge   True
6     xc2009@nyu.edu                                  pairup/matchforge   True
24   am12611@nyu.edu                                             planit  False
26   ayl2063@nyu.edu                                             planit  False
25    ka2859@nyu.edu                                             planit  False
60    ae2506@nyu.edu                                         pocketplan  False
67  cac10199@nyu.edu                                         pocketplan  False
68    lk3104@nyu.edu                                         pocketplan  False
62    ma7759@nyu.edu                                         pocketplan  False
61    sn3665@nyu.edu                                         pocketplan  False
64    bl3279@nyu.edu                                        skill swipe  False
44   fcw2020@nyu.edu                                        skill swipe  False
31    kw3224@nyu.edu                         stop booking start cooking  False
32    tk2830@nyu.edu                         stop booking start cooking  False
33    yl9814@nyu.edu                         stop booking start cooking  False
9      nz768@nyu.edu                         stop booking start cooking   True
43    co2323@nyu.edu                            student expense tracker  False
42   naa9453@nyu.edu                            student expense tracker  False
57    sd4994@nyu.edu                            student expense tracker  False
41    sg7789@nyu.edu                            student expense tracker  False
15   sia4979@nyu.edu                            student expense tracker   True
53    al8230@nyu.edu                                          studyspot  False
27    hc4893@nyu.edu                                          studyspot  False
28    jp6393@nyu.edu                                          studyspot  False
45    jm9908@nyu.edu                                          studysync  False
16   jbc9970@nyu.edu                                          studysync   True
18    mw4725@nyu.edu                                          studysync   True
17   rab9635@nyu.edu                                          studysync   True
65    cl6577@nyu.edu                                             subvet  False
20   laa9624@nyu.edu                                               swap   True
49   am14384@nyu.edu                                          syllabus+  False
50    mn3433@nyu.edu                                          syllabus+  False
66    ra4150@nyu.edu                                          syllabus+  False
51   ymm9035@nyu.edu                                          syllabus+  False
21   mm13520@nyu.edu                                          syllabus+   True
58    ml9389@nyu.edu                                               vixu  False
59    tn2272@nyu.edu                                               vixu  False

## Eliminate teams with too few members

All teams by number of members

In [56]:
team_counts = df_assignments['project'].value_counts().sort_values(ascending=False)
print(team_counts)

project
budgetlife                                                  5
pocketplan                                                  5
pairup/matchforge                                           5
student expense tracker                                     5
syllabus+                                                   5
feedbackloop                                                5
internbuddy                                                 5
studysync                                                   4
capturing                                                   4
stop booking start cooking                                  4
studyspot                                                   3
meetpoint                                                   3
planit                                                      3
newstoaction                                                2
jamsesh                                                     2
skill swipe                                                 2
vixu                                                        2
paddock                                                     2
swap                                                        1
healthmate – practical health and fitness management app    1
subvet                                                      1
Name: count, dtype: int64

Too few votes

In [57]:
insufficient_projects = team_counts[team_counts < STUDENTS_PER_TEAM]
insufficient_projects

project
studysync                                                   4
capturing                                                   4
stop booking start cooking                                  4
studyspot                                                   3
meetpoint                                                   3
planit                                                      3
newstoaction                                                2
jamsesh                                                     2
skill swipe                                                 2
vixu                                                        2
paddock                                                     2
swap                                                        1
healthmate – practical health and fitness management app    1
subvet                                                      1
Name: count, dtype: int64

In [58]:
# Replace project names in df_assignments that are in insufficient_projects with 'unassigned'
df_assignments.loc[df_assignments['project'].isin(insufficient_projects.index), 'project'] = np.nan
df_assignments

               email                  project    own
0    aa10027@nyu.edu               budgetlife   True
1    zyc2270@nyu.edu               budgetlife   True
2     yw6861@nyu.edu               budgetlife   True
3     jk8308@nyu.edu        pairup/matchforge   True
4     rm6283@nyu.edu        pairup/matchforge   True
5     el3798@nyu.edu        pairup/matchforge   True
6     xc2009@nyu.edu        pairup/matchforge   True
7    sl10716@nyu.edu        pairup/matchforge   True
8    san7576@nyu.edu                      NaN   True
9      nz768@nyu.edu                      NaN   True
10    sz3832@nyu.edu             feedbackloop   True
11    aw5287@nyu.edu              internbuddy   True
12    fl2367@nyu.edu              internbuddy   True
13    gh2313@nyu.edu              internbuddy   True
14    st4966@nyu.edu              internbuddy   True
15   sia4979@nyu.edu  student expense tracker   True
16   jbc9970@nyu.edu                      NaN   True
17   rab9635@nyu.edu                      NaN   True
18    mw4725@nyu.edu                      NaN   True
19    sy3544@nyu.edu                      NaN   True
20   laa9624@nyu.edu                      NaN   True
21   mm13520@nyu.edu                syllabus+   True
22    mw5608@nyu.edu                      NaN   True
23    tq2098@nyu.edu                      NaN   True
24   am12611@nyu.edu                      NaN  False
25    ka2859@nyu.edu                      NaN  False
26   ayl2063@nyu.edu                      NaN  False
27    hc4893@nyu.edu                      NaN  False
28    jp6393@nyu.edu                      NaN  False
29    ml8397@nyu.edu               budgetlife  False
30    st4816@nyu.edu               budgetlife  False
31    kw3224@nyu.edu                      NaN  False
32    tk2830@nyu.edu                      NaN  False
33    yl9814@nyu.edu                      NaN  False
34   jaj9365@nyu.edu             feedbackloop  False
35    ag8969@nyu.edu             feedbackloop  False
36   ngm9720@nyu.edu             feedbackloop  False
37    fh2303@nyu.edu             feedbackloop  False
38    aw5571@nyu.edu              internbuddy  False
39   itd2007@nyu.edu                      NaN  False
40    lj1353@nyu.edu                      NaN  False
41    sg7789@nyu.edu  student expense tracker  False
42   naa9453@nyu.edu  student expense tracker  False
43    co2323@nyu.edu  student expense tracker  False
44   fcw2020@nyu.edu                      NaN  False
45    jm9908@nyu.edu                      NaN  False
46    hj2743@nyu.edu                      NaN  False
47    at6055@nyu.edu                      NaN  False
48     wg823@nyu.edu                      NaN  False
49   am14384@nyu.edu                syllabus+  False
50    mn3433@nyu.edu                syllabus+  False
51   ymm9035@nyu.edu                syllabus+  False
52   smh9864@nyu.edu                      NaN  False
53    al8230@nyu.edu                      NaN  False
54    up2040@nyu.edu                      NaN  False
55   dpp9951@nyu.edu                      NaN  False
56   knp4830@nyu.edu                      NaN  False
57    sd4994@nyu.edu  student expense tracker  False
58    ml9389@nyu.edu                      NaN  False
59    tn2272@nyu.edu                      NaN  False
60    ae2506@nyu.edu               pocketplan  False
61    sn3665@nyu.edu               pocketplan  False
62    ma7759@nyu.edu               pocketplan  False
63    lcs493@nyu.edu                      NaN  False
64    bl3279@nyu.edu                      NaN  False
65    cl6577@nyu.edu                      NaN  False
66    ra4150@nyu.edu                syllabus+  False
67  cac10199@nyu.edu               pocketplan  False
68    lk3104@nyu.edu               pocketplan  False

In [59]:
team_counts = df_assignments['project'].value_counts().sort_values(ascending=False)
print(team_counts)

project
budgetlife                 5
pairup/matchforge          5
feedbackloop               5
internbuddy                5
student expense tracker    5
syllabus+                  5
pocketplan                 5
Name: count, dtype: int64

In [60]:
# Find rows with null project
null_project_mask = df_assignments['project'].isnull()
num_nulls = null_project_mask.sum()
num_nulls

np.int64(34)

In [61]:
import math

num_groups = math.ceil(num_nulls / STUDENTS_PER_TEAM)
num_groups

7

Generate random team names for those unassigned so far

In [62]:
import nltk
import random

nltk.download('words')
from nltk.corpus import words

word_list = [w for w in words.words() if len(w) > 4]
random_names = [
    "team_" + random.choice(word_list).lower()
    for _ in range(num_groups)
]
random_names

[nltk_data] Downloading package words to
[nltk_data]     /Users/foobarstein/nltk_data...
[nltk_data]   Package words is already up-to-date!

['team_triplewise',
 'team_pageless',
 'team_nonrhythmic',
 'team_stereoscopically',
 'team_subparallel',
 'team_unincited',
 'team_macrobiotics']

Assign the random team names to those students who are unassigned.

In [63]:
# Assign random project names in groups
null_indices = df_assignments[null_project_mask].index.tolist()
for i, idx in enumerate(null_indices):
    group_num = i // STUDENTS_PER_TEAM
    df_assignments.at[idx, 'project'] = random_names[group_num]
df_assignments

               email                  project    own
0    aa10027@nyu.edu               budgetlife   True
1    zyc2270@nyu.edu               budgetlife   True
2     yw6861@nyu.edu               budgetlife   True
3     jk8308@nyu.edu        pairup/matchforge   True
4     rm6283@nyu.edu        pairup/matchforge   True
5     el3798@nyu.edu        pairup/matchforge   True
6     xc2009@nyu.edu        pairup/matchforge   True
7    sl10716@nyu.edu        pairup/matchforge   True
8    san7576@nyu.edu          team_triplewise   True
9      nz768@nyu.edu          team_triplewise   True
10    sz3832@nyu.edu             feedbackloop   True
11    aw5287@nyu.edu              internbuddy   True
12    fl2367@nyu.edu              internbuddy   True
13    gh2313@nyu.edu              internbuddy   True
14    st4966@nyu.edu              internbuddy   True
15   sia4979@nyu.edu  student expense tracker   True
16   jbc9970@nyu.edu          team_triplewise   True
17   rab9635@nyu.edu          team_triplewise   True
18    mw4725@nyu.edu          team_triplewise   True
19    sy3544@nyu.edu            team_pageless   True
20   laa9624@nyu.edu            team_pageless   True
21   mm13520@nyu.edu                syllabus+   True
22    mw5608@nyu.edu            team_pageless   True
23    tq2098@nyu.edu            team_pageless   True
24   am12611@nyu.edu            team_pageless  False
25    ka2859@nyu.edu         team_nonrhythmic  False
26   ayl2063@nyu.edu         team_nonrhythmic  False
27    hc4893@nyu.edu         team_nonrhythmic  False
28    jp6393@nyu.edu         team_nonrhythmic  False
29    ml8397@nyu.edu               budgetlife  False
30    st4816@nyu.edu               budgetlife  False
31    kw3224@nyu.edu         team_nonrhythmic  False
32    tk2830@nyu.edu    team_stereoscopically  False
33    yl9814@nyu.edu    team_stereoscopically  False
34   jaj9365@nyu.edu             feedbackloop  False
35    ag8969@nyu.edu             feedbackloop  False
36   ngm9720@nyu.edu             feedbackloop  False
37    fh2303@nyu.edu             feedbackloop  False
38    aw5571@nyu.edu              internbuddy  False
39   itd2007@nyu.edu    team_stereoscopically  False
40    lj1353@nyu.edu    team_stereoscopically  False
41    sg7789@nyu.edu  student expense tracker  False
42   naa9453@nyu.edu  student expense tracker  False
43    co2323@nyu.edu  student expense tracker  False
44   fcw2020@nyu.edu    team_stereoscopically  False
45    jm9908@nyu.edu         team_subparallel  False
46    hj2743@nyu.edu         team_subparallel  False
47    at6055@nyu.edu         team_subparallel  False
48     wg823@nyu.edu         team_subparallel  False
49   am14384@nyu.edu                syllabus+  False
50    mn3433@nyu.edu                syllabus+  False
51   ymm9035@nyu.edu                syllabus+  False
52   smh9864@nyu.edu         team_subparallel  False
53    al8230@nyu.edu           team_unincited  False
54    up2040@nyu.edu           team_unincited  False
55   dpp9951@nyu.edu           team_unincited  False
56   knp4830@nyu.edu           team_unincited  False
57    sd4994@nyu.edu  student expense tracker  False
58    ml9389@nyu.edu           team_unincited  False
59    tn2272@nyu.edu        team_macrobiotics  False
60    ae2506@nyu.edu               pocketplan  False
61    sn3665@nyu.edu               pocketplan  False
62    ma7759@nyu.edu               pocketplan  False
63    lcs493@nyu.edu        team_macrobiotics  False
64    bl3279@nyu.edu        team_macrobiotics  False
65    cl6577@nyu.edu        team_macrobiotics  False
66    ra4150@nyu.edu                syllabus+  False
67  cac10199@nyu.edu               pocketplan  False
68    lk3104@nyu.edu               pocketplan  False

In [64]:
# Display the number of students assigned to each team, sorted descending
df_assignments['project'].value_counts().sort_values(ascending=False)

project
budgetlife                 5
pairup/matchforge          5
team_triplewise            5
feedbackloop               5
internbuddy                5
student expense tracker    5
team_pageless              5
syllabus+                  5
team_nonrhythmic           5
team_stereoscopically      5
team_subparallel           5
team_unincited             5
pocketplan                 5
team_macrobiotics          4
Name: count, dtype: int64

## Normalize team names
Put all team names into snake case.

In [ ]:
import re

def normalize_name(name):
    if pd.isna(name):
        return name
    s = str(name).lower()
    s = re.sub(r'[^a-z]+', '_', s)  # replace non-letters with underscore
    s = re.sub(r'_+', '_', s).strip('_')  # collapse and trim underscores
    return s

df_assignments['project'] = df_assignments['project'].apply(normalize_name)

# show resulting unique project names
df_assignments['project'].unique()

array(['budgetlife', 'pairup_matchforge', 'team_triplewise',
       'feedbackloop', 'internbuddy', 'student_expense_tracker',
       'team_pageless', 'syllabus', 'team_nonrhythmic',
       'team_stereoscopically', 'team_subparallel', 'team_unincited',
       'team_macrobiotics', 'pocketplan'], dtype=object)

## Save assignments
Save to CSV output data file.

In [66]:
df_assignments = df_assignments.sort_values(by=['project', 'own', 'email'], ascending=[True, False, True])
df_assignments.to_csv(OUTPUT_FILE, index=False)